<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <title>Track Lab</title>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="TrackLab" name="description"/>
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="/libs/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="/libs/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css"/>
        <link href="/libs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--    <link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>-->
        <!--    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>-->
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
        <!--    <link href="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>-->
        <!--    <link href="/assets/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css"/>-->
        <!--    <link href="/assets/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>-->
        <!--    <link href="/assets/global/plugins/morris/morris.css" rel="stylesheet" type="text/css">-->
        <!-- END PAGE LEVEL PLUGIN STYLES -->
        <!-- BEGIN PAGE STYLES -->
        <!--    <link href="/assets/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>-->
        <!-- END PAGE STYLES -->
        <!-- BEGIN THEME STYLES -->
        <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
        <link href="/css/template/components.css" id="style_components" rel="stylesheet" type="text/css"/>
        <link href="/assets/global/css/plugins-md.css" rel="stylesheet" type="text/css"/>
        <link href="/css/template/layout.css" rel="stylesheet" type="text/css"/>
        <link href="/css/template/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="/css/template/custom.css" rel="stylesheet" type="text/css"/>
        <link href="/libs/codemirror/lib/codemirror.css" rel="stylesheet" type="text/css"/>
        <link href="/libs/codemirror/theme/eclipse.css" rel="stylesheet" type="text/css"/>
        <link  href="/libs/angular-chart.js/dist/angular-chart.css" rel="stylesheet">
        <script src="/libs/codemirror/lib/codemirror.js" ></script>
        
        <script src="/libs/codemirror/mode/javascript/javascript.js"></script>
        <!-- END THEME STYLES -->
        <link href="/css/app.css" rel="stylesheet" type="text/css"/>
        <link rel="shortcut icon" href="favicon.ico"/>

        <base href="/" />
    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
    <!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
    <!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
    <!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
    <!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
    <!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
    <!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
    <body ng-controller="controllers.base" class="page-md page-header-fixed page-sidebar-closed-hide-logo page-sidebar-closed-hide-logo">
        <div class="page-spinner-bar" ng-show="$root.loadingPage">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
        <!-- BEGIN HEADER -->
        <div class="page-header md-shadow-z-1-i navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="/" style="text-decoration: none">
                        <h2>Track Lab</h2>
                    </a>
                    <div class="menu-toggler sidebar-toggler">
                        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                    </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN PAGE ACTIONS -->
                <!-- DOC: Remove "hide" class to enable the page header actions -->
                <div class="page-actions">
                    <div class="btn-group">
                        <button type="button" class="btn red-haze btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="hidden-sm hidden-xs" ng-bind="currentProject"></span>&nbsp;<i class="fa fa-angle-down"></i>
                        </button>

                        <ul class="dropdown-menu" role="menu">
                            <li ng-repeat="item in projects_menu" ng-class="{'active':item.name == currentProject}">
                                <a ng-click="changeProject(item)">
                                    <i class="{{item.icon}}"></i>
                                    <span class="title">{{item.text}}</span>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
                <!-- END PAGE ACTIONS -->
                <!-- END PAGE TOP -->
            </div>
            <!-- END HEADER INNER -->
        </div>
        <!-- END HEADER -->
        <div class="clearfix">
        </div>
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                <div class="page-sidebar md-shadow-z-2-i  navbar-collapse collapse">
                    <!-- BEGIN SIDEBAR MENU -->
                    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                    <ul ng-show="menu" class="page-sidebar-menu ng-hide" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                        <li ng-repeat="item in menu" ng-class="{'active':route == item.href}">
                            <a ng-href="{{item.href}}">
                                <i class="{{item.icon}}"></i>
                                <span class="title">{{item.text}}</span>
                                <span ng-class="{'arrow':item.submenu.length > 0}"></span>
                            </a>
                            <ul ng-show="item.submenu.length > 0" ng-class="{'sub-menu':item.submenu.length > 0}">
                                <li ng-repeat="item_submenu in item.submenu"  ng-class="{'active':route == item_submenu.href}">
                                    <a href="{{item_submenu.href}}"><i class="{{item_submenu.icon}}"></i> {{item_submenu.text}}</a>
                                </li>
                            </ul>
                        </li>
                    </ul><!-- END SIDEBAR MENU -->
                </div>
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content">
                    <!-- BEGIN PAGE HEAD -->
                    <div data-ng-view></div>
                    <!-- END PAGE HEAD -->
                    <!-- BEGIN ACTUAL CONTENT -->
                    <div ui-view class="fade-in-up">
                    </div>
                    <!-- END ACTUAL CONTENT -->
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner">
                2016 &copy; Track Lab. Iliya Garakh 
           </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>
        <!-- END FOOTER -->
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <script src="libs/requirejs/require.js" data-main="js/main.js"></script>

    </head>        
    <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>